### ISSUE TITLE
New redirect link

### ISSUE THREAD

**Issue by jesseilev** [LaunchCodeEducation/launchcodeeducation.github.io#1]
@terribleplan I changed the name of the St Louis repo, so the redirect link for http://education.launchcode.org/ now results in a 404.

I tried updating the links in this repo's [index.html](https://github.com/LaunchCodeEducation/launchcodeeducation.github.io/blob/master/index.html), but I still get redirected to the old url. Any ideas?

**Comment by terribleplan** [comment]
It is working for me now. It is likely a caching issue on your end, or it could be due to the fact that github doesn't update pages immediately.
